### ISSUE TITLE
Error panic: Failed to load mtmanapi dll.

### ISSUE THREAD

**Issue by tarikhagustia** [mikha-dev/mt4-go#1]
Hello, thanks for your job, any way i have problem when running this package. how to solve this problem
```
panic: Failed to load mtmanapi dll.
```

**Comment by mikha-dev** [comment]
you need to copy mtmanapi.dll to the same folder where you have .exe

**Comment by tarikhagustia** [comment]
hi @mikha-dev thanks for your feedback, i have fixed this issue by passing mtmanapi64.dll. but i have problem when get User list from UserRequest function. i have function like this
```
total := 0
users = mtapi.UsersRequest(&total)
for i := 0; i < total; i++ { 
  usr := mtmanapi. UserRecordArray_getitem(users, i)
  fmt.Print(usr.GetName())
}
```

when call `GetName()` error `slice bounds out of range` appear. any idea with this?

**Comment by mikha-dev** [comment]
yo need 32 version of that dll, 64 is very unstable (also that error with
string convesion). also you need to build your go code with 386 flag. i use
gox too for that.

**Comment by tarikhagustia** [comment]
i see, i got error when running this command
```
gox -osarch="windows/386" ./
```
error : 
```
--> windows/386 error: exit status 1
Stderr: can't load package: package .: build constraints exclude all Go files in
```

**Comment by tarikhagustia** [comment]
thanks bro, you are awesome @mikha-dev, reinstalling go to 32 bit version and its work. anyway do you know how to handle uintptr data when using Pump Mode? lets say i want to get Updated users in Pump mode

**Comment by mikha-dev** [comment]
you need to use wrappers from SWIG code.

when pump is
func (m *MarketManager) OnPump(code, typ int, data, param uintptr) {
switch {
case code == mtmanapi.PUMP_UPDATE_USERS:
u := mtmanapi.UserRecord(mtmanapi.SwigcptrUserRecord(data))
default:
}
}

**Comment by tarikhagustia** [comment]
Thanks u bruh u save my time to code with c++ 😁

**Comment by tarikhagustia** [comment]
hi @mikha-dev , i'm stuck on this function
```
func (meta MetaController) GetAccount(c *gin.Context) {
	total := 0
	login := 1
	usr := meta.MtAPI.UserRecordsRequest(login, &total)
	log.Println(usr)
	log.Println(total)
	c.JSON(200, "user")
}
```
on Metaqutes documentation function UserRecordsRequest need array of login, but when use in go this function require *int variable, my question is how to create array and store it on *int data type? thanks

**Comment by mikha-dev** [comment]
usr := meta.UserRecordsRequest(*&*login, &total)
the rest is correct

**Comment by tarikhagustia** [comment]
after trying im getting total value = 0

**Comment by mikha-dev** [comment]
then issue with login, it is wrong. The code is correct and I use it in
production.

**Comment by tarikhagustia** [comment]
after adding `*&*loginn` this error message apper `invalid indirect of loginn (type int)`invalid indirect of loginn (type int)
```
total := 0
loginn := 6971
usr := meta.MtAPI.UserRecordsRequest(*&*loginn, &total)
log.Println(usr)
log.Println(total)
```

**Comment by mikha-dev** [comment]
total := 0
login := 6971
usr := meta.MtAPI.UserRecordsRequest(&login, &total)
log.Println(usr)
log.Println(total)

**Comment by tarikhagustia** [comment]
hi @mikha-dev , finally im using AdmUserRequest to get user information, but i have some problem when creating rest full api using gin. when we hit api at same time (for this case with 10 hit at same time). the mtmanager api return error and cannot call the function, i think because connection between go and mt4 was disconnect, any idea with this? thanks

**Comment by KnBrBz** [comment]
> hi @mikha-dev , finally im using AdmUserRequest to get user information, but i have some problem when creating rest full api using gin. when we hit api at same time (for this case with 10 hit at same time). the mtmanager api return error and cannot call the function, i think because connection between go and mt4 was disconnect, any idea with this? thanks

As far as I know, there is a limit for amount of requests for manager api
